# Generated by Django 5.2 on 2026-02-28 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('service_provider', 'Fournisseur de services'), ('client_provider', 'Fournisseur client'), ('admin', 'Administrateur')], default='service_provider', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('preferred_service_areas', models.JSONField(default=list)),
                ('average_monthly_requests', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SeekerProfile',
        ),
    ]
