# Generated by Django 5.2 on 2026-03-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type_clientproviderprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='est_verifie',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_utilisateur',
            field=models.CharField(choices=[('prestataire', 'Prestataire de services'), ('fournisseur', 'Fournisseur de services'), ('administrateur', 'Administrateur')], default='prestataire', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.CreateModel(
            name='ProfileFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('secteur_activite', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('taille_entreprise', models.CharField(blank=True, max_length=50, verbose_name="Taille de l'entreprise")),
                ('demandes_services', models.JSONField(default=list, verbose_name='Types de services demandés')),
                ('prestataires_preferes', models.JSONField(default=list, verbose_name='Prestataires préférés')),
                ('plage_budget', models.JSONField(default=dict, verbose_name='Plage de budget habituelle')),
                ('frequence_services', models.CharField(blank=True, max_length=50, verbose_name='Fréquence des services')),
                ('contact_principal', models.CharField(blank=True, max_length=100, verbose_name='Contact principal')),
                ('mode_paiement_preferes', models.JSONField(default=list, verbose_name='Modes de paiement préférés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fournisseur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil de fournisseur',
                'verbose_name_plural': 'Profils de fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('types_prestations', models.JSONField(default=list, verbose_name='Types de prestations proposées')),
                ('zones_couverture', models.JSONField(default=list, verbose_name='Zones de couverture')),
                ('annees_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('certifications', models.JSONField(default=list, verbose_name='Certifications et licences')),
                ('assurance_valide', models.BooleanField(default=False, verbose_name='Assurance valide')),
                ('note', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note')),
                ('prestations_effectuees', models.PositiveIntegerField(default=0, verbose_name='Prestations effectuées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_prestataire', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil de prestataire',
                'verbose_name_plural': 'Profils de prestataires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClientProviderProfile',
        ),
        migrations.DeleteModel(
            name='ProviderProfile',
        ),
    ]
