# Generated by Django 5.2 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_providerprofile_user_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefournisseur',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profileprestataire',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profileprestataire',
            name='note',
        ),
        migrations.AddField(
            model_name='profileprestataire',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
    ]
