# Generated by Django 4.2.7 on 2026-04-12 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_utilisateur_profilefournisseur_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('secteur_activite', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('taille_entreprise', models.CharField(blank=True, max_length=50, verbose_name="Taille de l'entreprise")),
                ('besoins_services', models.JSONField(default=list, verbose_name='Types de services recherchés')),
                ('fournisseurs_preferes', models.JSONField(default=list, verbose_name='Fournisseurs préférés')),
                ('plage_budget', models.JSONField(default=dict, verbose_name='Plage de budget habituelle')),
                ('frequence_demandes', models.CharField(blank=True, max_length=50, verbose_name='Fréquence des demandes')),
                ('contact_principal', models.CharField(blank=True, max_length=100, verbose_name='Contact principal')),
                ('mode_paiement_preferes', models.JSONField(default=list, verbose_name='Modes de paiement préférés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Profil de client',
                'verbose_name_plural': 'Profils de clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='contact_principal',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='demandes_services',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='frequence_services',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='mode_paiement_preferes',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='plage_budget',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='prestataires_preferes',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='secteur_activite',
        ),
        migrations.RemoveField(
            model_name='profilefournisseur',
            name='taille_entreprise',
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='annees_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='assurance_valide',
            field=models.BooleanField(default=False, verbose_name='Assurance valide'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='certifications',
            field=models.JSONField(default=list, verbose_name='Certifications et licences'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='disponibilites',
            field=models.JSONField(default=dict, verbose_name='Disponibilités'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='services_effectues',
            field=models.PositiveIntegerField(default=0, verbose_name='Services effectués'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='tarif_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarif horaire'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='types_services_offerts',
            field=models.JSONField(default=list, verbose_name='Types de services offerts'),
        ),
        migrations.AddField(
            model_name='profilefournisseur',
            name='zones_couverture',
            field=models.JSONField(default=list, verbose_name='Zones de couverture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_utilisateur',
            field=models.CharField(choices=[('client', 'Client - Exprime les besoins'), ('fournisseur', 'Fournisseur - Offre les services'), ('administrateur', 'Administrateur')], default='client', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.DeleteModel(
            name='ProfilePrestataire',
        ),
        migrations.AddField(
            model_name='profileclient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_client', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
