# Generated by Django 5.2 on 2026-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_emplacement_to_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='frequence_besoins',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fréquence des besoins'),
        ),
    ]
