# Generated by Django 5.2 on 2026-02-28 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceneed',
            name='seeker',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='seeker',
        ),
        migrations.AddField(
            model_name='serviceneed',
            name='client_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='client_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_provider_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
