# Generated by Django 4.2.7 on 2026-03-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_serviceneed_seeker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceneed',
            old_name='client_provider',
            new_name='client',
        ),
    ]
