# Generated by Django 4.2.7 on 2026-03-01 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_rename_client_provider_serviceneed_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetransaction',
            old_name='client_provider',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='serviceneed',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_needs', to=settings.AUTH_USER_MODEL),
        ),
    ]
