# Generated by Django 5.2 on 2026-03-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_client_provider_servicetransaction_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceneed',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serviceneed',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='need',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='contenu',
            field=models.TextField(default='', verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sujet'),
        ),
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.categorieservice', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé de la demande')),
                ('description', models.TextField(verbose_name='Description du besoin')),
                ('type_service', models.CharField(max_length=100, verbose_name='Type de service recherché')),
                ('exigences', models.JSONField(default=dict, verbose_name='Exigences spécifiques')),
                ('lieu_intervention', models.CharField(max_length=200, verbose_name="Lieu d'intervention")),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('date_limite', models.DateTimeField(blank=True, null=True, verbose_name='Date limite')),
                ('urgence', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name="Niveau d'urgence")),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('flexible', models.BooleanField(default=False, verbose_name='Flexible')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('pourvue', 'Pourvue'), ('annulee', 'Annulée')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='services.categorieservice', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Demande de service',
                'verbose_name_plural': 'Demandes de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé de la prestation')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_prestation', models.CharField(max_length=100, verbose_name='Type de prestation')),
                ('caracteristiques', models.JSONField(default=dict, verbose_name='Caractéristiques techniques')),
                ('zones_intervention', models.JSONField(default=list, verbose_name="Zones d'intervention")),
                ('disponibilite_debut', models.DateTimeField(blank=True, null=True, verbose_name='Début de disponibilité')),
                ('disponibilite_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de disponibilité')),
                ('mode_tarification', models.CharField(choices=[('fixe', 'Tarif fixe'), ('horaire', 'Tarif horaire'), ('forfait', 'Forfait'), ('devis', 'Sur devis')], default='fixe', max_length=50, verbose_name='Mode de tarification')),
                ('tarif_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif minimum')),
                ('tarif_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif maximum')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='services.categorieservice', verbose_name='Catégorie')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Prestation de service',
                'verbose_name_plural': 'Prestations de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix final')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('debut_confirme', models.BooleanField(default=False, verbose_name='Début confirmé')),
                ('fin_confirmee', models.BooleanField(default=False, verbose_name='Fin confirmée')),
                ('heure_debut', models.DateTimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.demande', verbose_name='Demande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Fournisseur')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.prestation', verbose_name='Prestation')),
            ],
            options={
                'verbose_name': 'Transaction de service',
                'verbose_name_plural': 'Transactions de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='services.transactionservice', verbose_name='Transaction'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
