# Generated by Django 5.2 on 2026-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_matchingscore_need_alter_matchingscore_offer'),
        ('services', '0005_remove_serviceneed_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceNeed',
        ),
        migrations.DeleteModel(
            name='ServiceOffer',
        ),
        migrations.DeleteModel(
            name='ServiceTransaction',
        ),
    ]
