# Generated by Django 5.2 on 2026-04-29 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_demande_to_besoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='besoin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Besoin de service', 'verbose_name_plural': 'Besoins de services'},
        ),
        migrations.AlterField(
            model_name='besoin',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins', to='services.categorieservice', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='intitule',
            field=models.CharField(max_length=200, verbose_name='Intitulé du besoin'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to=settings.AUTH_USER_MODEL, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='transactionservice',
            name='besoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.besoin', verbose_name='Besoin'),
        ),
        migrations.AlterField(
            model_name='transactionservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_comme_client', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='transactionservice',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_comme_fournisseur', to=settings.AUTH_USER_MODEL, verbose_name='Fournisseur'),
        ),
    ]
