# Generated by Django 5.2 on 2026-05-06 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_split_subcategory_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionservice',
            name='demande_validation_admin',
            field=models.BooleanField(default=False, verbose_name='Validation admin demandée'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='demande_validation_admin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date demande validation admin'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='travail_fournisseur_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date travail terminé'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='travail_fournisseur_termine',
            field=models.BooleanField(default=False, verbose_name='Travail fournisseur terminé'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='validation_admin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation admin'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='validation_admin_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_validees_admin', to=settings.AUTH_USER_MODEL, verbose_name='Validée par admin'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='validation_admin_statut',
            field=models.CharField(choices=[('non_requise', 'Non requise'), ('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='non_requise', max_length=20, verbose_name='Statut validation admin'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='verification_client_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date vérification client'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='verification_client_effectuee',
            field=models.BooleanField(default=False, verbose_name='Vérification client effectuée'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='verification_client_validee',
            field=models.BooleanField(default=False, verbose_name='Vérification client validée'),
        ),
    ]
