# Generated by Django 5.2 on 2026-05-07 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_transactionservice_demande_validation_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='mode_budget',
            field=models.CharField(choices=[('budget_fixe', 'Budget fixe'), ('sur_devis', 'Sur devis')], default='budget_fixe', max_length=20, verbose_name='Mode budget'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_date_proposition',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date proposition devis'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_date_reponse_client',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date réponse client devis'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_description',
            field=models.TextField(blank=True, verbose_name='Description devis'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_montant_propose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant devis proposé'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_propose_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_devis_proposes', to=settings.AUTH_USER_MODEL, verbose_name='Devis proposé par'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='devis_statut',
            field=models.CharField(choices=[('non_requis', 'Non requis'), ('a_proposer', 'À proposer'), ('en_attente_client', 'En attente client'), ('accepte_client', 'Accepté par le client'), ('rejete_client', 'Rejeté par le client')], default='non_requis', max_length=20, verbose_name='Statut devis'),
        ),
    ]
