# Generated by Django 6.0.2 on 2026-02-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('route', 'Correspondance de route'), ('capacity', 'Capacité du véhicule'), ('availability', 'Disponibilité'), ('price', 'Fourchette de prix')], max_length=20)),
                ('conditions', models.JSONField()),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.serviceneed')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.serviceoffer')),
            ],
            options={
                'indexes': [models.Index(fields=['score'], name='matching_ma_score_f4461a_idx'), models.Index(fields=['calculated_at'], name='matching_ma_calcula_6db052_idx')],
                'unique_together': {('offer', 'need')},
            },
        ),
    ]
