# Generated by Django 5.2 on 2026-03-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('services', '0005_remove_serviceneed_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingscore',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.demande'),
        ),
        migrations.AlterField(
            model_name='matchingscore',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.prestation'),
        ),
    ]
