# Generated by Django 5.2 on 2026-04-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matchingscore_need_besoin'),
        ('services', '0009_alter_besoin_options_alter_besoin_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingscore',
            name='need',
            field=models.ForeignKey(db_column='need_id', on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.besoin'),
        ),
        migrations.RenameField(
            model_name='matchingscore',
            old_name='need',
            new_name='besoin',
        ),
        migrations.AlterField(
            model_name='matchingscore',
            name='offer',
            field=models.ForeignKey(db_column='offer_id', on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='services.prestation'),
        ),
        migrations.RenameField(
            model_name='matchingscore',
            old_name='offer',
            new_name='prestation',
        ),
        migrations.AlterUniqueTogether(
            name='matchingscore',
            unique_together={('prestation', 'besoin')},
        ),
    ]
